# Generated by Django 5.2.17 on 2026-10-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('deadline', 'Deadline'), ('eligibility', 'Eligibility'), ('required_documents', 'Required Documents'), ('specifications_quantities', 'Specifications Quantities'), ('pricing_format', 'Pricing Format'), ('submission_method', 'Submission Method')], max_length=40)),
                ('old_quote', models.TextField(blank=True)),
                ('new_quote', models.TextField(blank=True)),
                ('affects_user', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='tenders.tenderversion')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tenders.tender')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='tenders.tenderversion')),
            ],
            options={
                'ordering': ['tender', 'to_version', 'pk'],
            },
        ),
    ]
