# Generated by Django 5.2.17 on 2026-10-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('email_forward', 'Email Forward')], default='upload', max_length=20)),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_sw', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_versions', to='core.storedfile')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tenders.tender')),
            ],
            options={
                'ordering': ['tender', 'version_no'],
                'constraints': [models.UniqueConstraint(fields=('tender', 'version_no'), name='unique_tender_version_no')],
            },
        ),
    ]
