# Generated by Django 5.2.17 on 2026-10-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('kra_tax_compliance', 'Kra Tax Compliance'), ('business_registration', 'Business Registration'), ('agpo_certificate', 'Agpo Certificate'), ('cr12', 'Cr12'), ('national_id', 'National Id'), ('audited_accounts', 'Audited Accounts'), ('bank_statement', 'Bank Statement'), ('business_permit', 'Business Permit'), ('other', 'Other')], default='other', max_length=40)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.storedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
