# Generated by Django 5.2.17 on 2026-10-04 02:37

import access.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_size', models.CharField(choices=[('standard', 'Standard'), ('large', 'Large'), ('larger', 'Larger')], default='standard', max_length=10)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('dyslexia_spacing', models.BooleanField(default=False)),
                ('prompt_seen', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('family', 'Family'), ('accountant', 'Accountant'), ('interpreter', 'Interpreter'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('permission', models.CharField(choices=[('view', 'View'), ('upload', 'Upload'), ('prepare', 'Prepare')], default='view', max_length=10)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('removed', 'Removed')], default='invited', max_length=10)),
                ('token', models.CharField(default=access.models.new_invite_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('helper_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helping', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelperActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('permission_changed', 'Permission Changed'), ('removed', 'Removed'), ('viewed_documents', 'Viewed Documents'), ('uploaded_document', 'Uploaded Document'), ('prepared_bid', 'Prepared Bid'), ('owner_confirmed_bid', 'Owner Confirmed Bid')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='access.helper')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=80)),
                ('event_kind', models.CharField(choices=[('briefing', 'Briefing'), ('site_visit', 'Site Visit')], max_length=20)),
                ('event_title', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('tender_reference', models.CharField(blank=True, max_length=100)),
                ('needs', models.JSONField(default=list)),
                ('other_need', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(default='en', max_length=2)),
                ('letter_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'event_key'), name='one_request_per_event')],
            },
        ),
        migrations.CreateModel(
            name='BidConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('confirmed', 'Confirmed')], default='prepared', max_length=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_confirmations', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_confirmations', to='tenders.tender')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_bids', to='access.helper')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'tender'), name='one_bid_per_tender')],
            },
        ),
    ]
