# Generated by Django 5.2.17 on 2026-10-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('kra_tax_compliance', 'Kra Tax Compliance'), ('business_registration', 'Business Registration'), ('agpo_certificate', 'Agpo Certificate'), ('cr12', 'Cr12'), ('national_id', 'National Id'), ('audited_accounts', 'Audited Accounts'), ('bank_statement', 'Bank Statement'), ('business_permit', 'Business Permit'), ('other', 'Other')], db_index=True, max_length=40)),
                ('reason', models.TextField()),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('illustrative', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['doc_type', '-year', 'pk'],
            },
        ),
    ]
