# Generated by Django 5.2.17 on 2026-10-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectioncase',
            name='doc_type',
            field=models.CharField(choices=[('kra_tax_compliance', 'Kra Tax Compliance'), ('business_registration', 'Business Registration'), ('agpo_certificate', 'Agpo Certificate'), ('cr12', 'Cr12'), ('national_id', 'National Id'), ('audited_accounts', 'Audited Accounts'), ('bank_statement', 'Bank Statement'), ('business_permit', 'Business Permit'), ('other', 'Other'), ('ncpwd_registration', 'Ncpwd Registration')], db_index=True, max_length=40),
        ),
    ]
